"""
Fragment API Python Library.

Async client for interacting with Fragment.com marketplace and Telegram services.
Supports Stars, Premium, Giveaways, Usernames, Numbers, and Gifts operations.
Now includes No-KYC mode via MarketApp API for cookieless operation.
"""

from FragmentAPI.client import FragmentClient
from FragmentAPI.storage.base import SessionStorage
from FragmentAPI.storage.file import FileSessionStorage
from FragmentAPI.storage.redis import RedisSessionStorage
from FragmentAPI.types.models import (
    AdsTopupResult,
    AdsWithdrawalConfirmResult,
    AdsWithdrawalInitResult,
    AdsRechargeResult,
    AuctionInfo,
    BatchItemResult,
    BatchResult,
    BidHistoryEntry,
    BidResult,
    EvmInvoice,
    EvmPaymentResult,
    GatewayPriceInfo,
    GatewayRechargeResult,
    GiftAttribute,
    GiftAttributeCategory,
    GiftAttributeValue,
    GiftCollection,
    GiftFiltersInfo,
    GiftInfo,
    GiftsResult,
    GiveawayPremiumResult,
    GiveawayStarsResult,
    LoginCodeResult,
    NoKycBatchResult,
    NumberInfo,
    NumbersResult,
    OfferResult,
    OwnerHistoryEntry,
    OfferHistoryEntry,
    PremiumPriceOption,
    PremiumPrices,
    PremiumResult,
    PremiumTransaction,
    PreparedTransaction,
    PreparedTransactionMessage,
    ProfileInfo,
    PurchaseItem,
    PurchaseResult,
    RecipientInfo,
    SessionInfo,
    StarsPrice,
    StarsPrices,
    StarsResult,
    StarsTransaction,
    SubscriptionResult,
    TerminateSessionsResult,
    TransactionResult,
    UsernameInfo,
    UsernamesResult,
    WalletInfo,
    DerivedWalletInfo,
)
from FragmentAPI.exceptions import (
    AmbiguousMnemonicError,
    AlreadySubscribedError,
    AnonymousNumberError,
    ConfigurationError,
    InvalidMnemonicError,
    CookieError,
    FragmentAPIError,
    FragmentError,
    FragmentPageError,
    MarketAppAPIError,
    OperationError,
    ParseError,
    PaidMessageLimitError,
    RetryExhaustedError,
    SessionStorageError,
    TransactionError,
    UnexpectedError,
    UserNotFoundError,
    VerificationError,
    WalletError,
)
from FragmentAPI.utils.mnemonic import derive_wallet, derive_wallet_accounts

__version__ = "12.1.0"
__author__ = "S1qwy"
__email__ = "S1qwy@internet.ru"

__all__ = [
    "__version__",
    "FragmentClient",
    "derive_wallet",
    "derive_wallet_accounts",
    "DerivedWalletInfo",
    "AmbiguousMnemonicError",
    "InvalidMnemonicError",
    "SessionStorage",
    "FileSessionStorage",
    "RedisSessionStorage",
    "AdsTopupResult",
    "AdsWithdrawalConfirmResult",
    "AdsWithdrawalInitResult",
    "AdsRechargeResult",
    "AlreadySubscribedError",
    "AnonymousNumberError",
    "AuctionInfo",
    "BatchItemResult",
    "BatchResult",
    "BidHistoryEntry",
    "BidResult",
    "ConfigurationError",
    "CookieError",
    "EvmInvoice",
    "EvmPaymentResult",
    "FragmentAPIError",
    "FragmentError",
    "FragmentPageError",
    "GatewayPriceInfo",
    "GatewayRechargeResult",
    "GiftAttribute",
    "GiftAttributeCategory",
    "GiftAttributeValue",
    "GiftCollection",
    "GiftFiltersInfo",
    "GiftInfo",
    "GiftsResult",
    "GiveawayPremiumResult",
    "GiveawayStarsResult",
    "LoginCodeResult",
    "MarketAppAPIError",
    "NoKycBatchResult",
    "NumberInfo",
    "NumbersResult",
    "OfferResult",
    "OperationError",
    "OwnerHistoryEntry",
    "OfferHistoryEntry",
    "ParseError",
    "PremiumPriceOption",
    "PremiumPrices",
    "PremiumResult",
    "PremiumTransaction",
    "PreparedTransaction",
    "PreparedTransactionMessage",
    "ProfileInfo",
    "PurchaseItem",
    "PaidMessageLimitError",
    "PurchaseResult",
    "RecipientInfo",
    "RetryExhaustedError",
    "SessionInfo",
    "SessionStorageError",
    "StarsPrice",
    "StarsPrices",
    "StarsResult",
    "StarsTransaction",
    "SubscriptionResult",
    "TerminateSessionsResult",
    "TransactionError",
    "TransactionResult",
    "UnexpectedError",
    "UsernameInfo",
    "UsernamesResult",
    "UserNotFoundError",
    "VerificationError",
    "WalletError",
    "WalletInfo",
]
